name: benchmarkpl
channels: 
  - conda-forge
  - omnia
dependencies:
    # Base depends
  - python
  - pip

    # Testing
  - pytest
  - pytest-cov
  - codecov

  - numpy
  - scipy
  - plotly
  - pandas
  - rdkit
  - svgutils
  - pint
  - tqdm
  - pyyaml
  - matplotlib
  - networkx
  - openforcefield

    # Pip-only installs
  - pip:
     - '--editable=git+https://github.com/openforcefield/PLBenchmarks.git@b050a84#egg=PLBenchmarks'

