name: benchmarkpl
channels:
  - plotly
  - conda-forge
  - omnia
dependencies:
    # Base depends
  - python
  - pip

    # Testing
  - pytest
  - pytest-cov
  - codecov

  - numpy
  - scipy
  - plotly
  - pandas
  - rdkit
  - svgutils
  - conda-forge::pint
  - tqdm
  - pyyaml
  - matplotlib
  - networkx
  - openforcefield
  - gitpython 
  - seaborn 
  - scikit-learn
  - plotly::plotly-orca
  - psutil

    # Pip-only installs
  - pip:
     - '--editable=git+https://github.com/openforcefield/PLBenchmarks.git@1974a3e#egg=PLBenchmarks'
     - '--editable=git+https://github.com/openforcefield/Arsenic.git@0dadc5c#egg=arsenic'

